version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@3.0.1

executors:
  gcp-docker:
    docker:
      - image: cimg/gcp:2023.02.1
    resource_class: medium
  
commands:
  tf-install:
    steps:
      - checkout
      - gcp-cli/setup
      - run:
           name: tf install
           command: |
                sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
                wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
                sudo gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
                echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
                sudo apt install terraform -y
                terraform -v
                echo $GCLOUD_SERVICE_KEY > terraform-sa.json

  tf-init-plan:
    steps:
      - run:
           name: terraform init & plan
           command: |
              terraform init -input=false -backend-config="bucket=tf-state-nomad-vijay" -backend-config="prefix=cci4-nomad"
              terraform plan -out tfapply

jobs:
 gcp-tf-plan:
    working_directory: /tmp/project
    #executor: gcp-docker
    executor: gcp-cli/machine
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/setup
      - tf-install
      - tf-init-plan
      - persist_to_workspace:
          root: .
          paths:
            - .

 gcp-tf-apply:
   executor: gcp-docker
   steps:
     - attach_workspace:
         at: .
     - tf-install
     - run:
         name: terraform
         command: |
           terraform init -input=false -backend-config="bucket=tf-state-nomad-vijay" -backend-config="prefix=cci4-nomad"
           terraform apply -auto-approve tfapply
         no_output_timeout: 3h     
     - persist_to_workspace:
         root: .
         paths:
           - .

workflows:
  tf-gcp-nomad:
    jobs:
      - gcp-tf-plan:
           context: org-gcp
      #- gcp-tf-apply:
      #     requires:
      #       - gcp-tf-plan
      #     context: org-gcp
           
